version: "3"

services:
  dev-poke-front:
    build: ./
    volumes:
      - "poke.front.repo:/repo"
    tty: true
    ports:
      - "3010:3000"
    env_file:
      - ./.env

volumes:
  poke.front.repo:
